control:
  enable_gui: true
  enable_sim: true
  keyboard:
    angle_step: 5
    enabled: false
    gripper_step: 10.0
    pos_step: 0.01
  mink:
    dt: 0.005
    enabled: true
    end_effector_site: tools_link
    lm_damping: 1.0
    max_iters: 20
    mujoco_scene: mink/examples/arm620/scene_dual.xml
    orientation_cost: 0.1
    orientation_error_threshold: 0.01
    position_cost: 1.0
    position_error_threshold: 0.01
    posture_cost: 0.0001
    solve_damping: 1.0e-05
  teleop_frame:
    ee_target_orientation_correction_euler_xyz_deg:
    - -90.0
    - 0.0
    - -90.0
    translation_euler_xyz_deg:
    - 0.0
    - 0.0
    - 180.0
  use_mink: true
  vr:
    enabled: true
    orientation_reference_mode: global_calibration
    orientation_reference_quat_xyzw:
      left:
      - -0.688984811615382
      - -0.25416233118532
      - 0.25527887326520443
      - -0.6289150464364865
      right:
      - 0.7493498926350431
      - 0.10668732040735462
      - -0.13440800137239384
      - 0.6395522208852271
gnirehtet:
  args: []
  binary: gnirehtet-rust-linux64/gnirehtet
  enabled: false
  mode: run
gripper:
  closed_angle: 45.0
  open_angle: 0.0
ik:
  hysteresis_threshold: 0.05
  initial_joint_positions_deg:
    left:
    - 90.0
    - 30.0
    - 90.0
    - 90.0
    - 90.0
    - 150.0
    right:
    - -90.0
    - -30.0
    - -90.0
    - -90.0
    - -90.0
    - 30.0
  initial_reached_tolerance_deg: 6.0
  movement_penalty_weight: 0.01
  position_error_threshold: 0.01
  use_reference_poses: true
network:
  host_ip: 0.0.0.0
  https_port: 8443
  websocket_port: 8442
paths:
  urdf_path: mink/examples/arm620/urdf/arm620.urdf
robot:
  arm_controller:
    interpolation_alpha: 0.35
    left_mapping: left_arm
    max_step_deg: 6.0
    module_dir: ''
    right_mapping: right_arm
    workspace: /home/nvidia/Projects/universal-arm-controller
  command_backend: ros2_topic
  left_arm:
    enabled: true
    interface: rclpy
    name: Left ARM620
  require_joint_state_for_motion: true
  require_state_feedback: true
  right_arm:
    enabled: true
    interface: rclpy
    name: Right ARM620
  ros2:
    aggregate_joint_cmd_topic: /joint_target
    left_joint_cmd_topic: /left/joint_target
    left_joint_state_topic: /left/joint_states_sim
    right_joint_cmd_topic: /right/joint_target
    right_joint_state_topic: /right/joint_states_sim
  send_interval: 0.001
  vr_to_robot_scale: 1
ssl:
  certfile: cert.pem
  keyfile: key.pem
